### ISSUE TITLE
The info route and startup log messages should be consistent

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#300]
The Conseil and Lorre logs include startup messages of this form which are very helpful for support and debugging:

![image](https://user-images.githubusercontent.com/931163/55129583-fc303600-50ed-11e9-940b-3dabc6bbfbc8.png)

The `info` route returns slightly different information:

```json
{
    "version": "0.1912.0004",
    "application": "Conseil"
}
```

Could both return the same superset of data?

What do you think, @ivanopagano and @anonymoussprocket ?

**Comment by ivanopagano** [comment]
My point of view.
- The startup message is for internal "devops" to know exactly what to look for in a development run, usually when we're testing new stuff.
- The endpoint information is more targeted to generic user of the platform, so that he can have a quick reference to a *stable* release she's running.
  It's also an easy-to-use health endpoint for any cloud monitoring/orchestration solution to check.

**Comment by ivanopagano** [comment]
Please re-open if you have any argument against my approach, as outlined above
@vishakh
