### ISSUE TITLE
Conseil should log all incoming queries

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#317]
All queries received by Conseil should be logged into a table called `api_queries`. The columns of this table should be:
- Timestamp
- IP address (if possible)
- URL
- Query body
- API key
- API version (v1 or v2)
- HTTP response code
- Processing time
- Result set size (if not too complicated to do)

**Comment by piotrkosecki** [comment]
I've pushed branch with what I presented yesterday: https://github.com/Cryptonomic/Conseil/tree/poc_elk 
If we are going to go for it please tell me what additional changes should be done which may have came up after yesterdays presentation.
I believe this task will require also devops support, because the `logback.xml` should be overridden not pushed as it is because running the same version will cause every developer to send the logs to logstash, which we would not want to. Also below I've pasted the filters I've added to `logstash.conf`: 
```
filter{
    json{
        source => "message"
    }
    mutate {
       convert => { "responseCode" => "integer" }
       convert => { "responseTime" => "integer" }
    }
}
```
