### ISSUE TITLE
High cardinality field cache

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#347]
Add new parameters to the extended metadata overrides file. A flag to specific that a field should be cached. A field to specify a minimum number of characters to match on, for example for pkh (address), it should be at least 4 because addresses start with known 3-letter prefixes like tz1, etc. A field to specify a maximum number of matches to return. For example, there may be more than a thousand matches for 'tz1a', we likely want to see just two dozen of the first ones.

**Comment by piotrkosecki** [comment]
Let's specify additional fields:
```
cached: Boolean
minMatchLength: Int
maxResults: Int
```
1. I assume if `cached` is set to `false` or not exists we should omit rest of the parameters, am I right?
2. If `cached` is set to `true` and other parameters not exist should `minMatchLength` have default value 1(meaning starting matching from the first character entered) and amount of returned results not limited?
3. What should be the error code returned when length of a string matched is less than `minMatchLength`?
4. Should caching be added into all fields in development config, or only to the specific fields?
5. I assume that lexicographic order is expected for returning results, am I right?
So that's all question I could think of for now.

Regarding implementation detail I was thinking about using `prefix tree` also know as `trie` https://en.wikipedia.org/wiki/Trie - I'm not sure if it will meet all of our expectations but I think this would be a good place to start.
