### ISSUE TITLE
Expose ballot voting data

### ISSUE THREAD

**Issue by klassare** [Cryptonomic/Conseil#484]
Some ballot voting data is not exposed in ConseilJS.

It's particularly these RPC routes that would be of interest:
- /chains/main/blocks/head/votes/ballots
- /chains/main/blocks/head/votes/listings

It would be convenient with a function in ConseilJS that returned the data from the /votes/ballots route and also attached the number of unused votes. The data from votes/listings could be merged into getBallots(), so it returned {pkh, ballot, rolls, block_id, block_level} instead.

**Comment by anonymoussprocket** [comment]
related to #452

**Comment by AndreasGassmann** [comment]
I'm commenting here because it might be related:

Is there a reason why the ballot operations do not include fields like "source" or "fee"?

**Comment by klassare** [comment]
You have 4 different categories of operations. Voting related operations like ballot doesn't have a fee. In this case source should be the same as pkh.

**Comment by AndreasGassmann** [comment]
So there's no fee, thanks.

Maybe I'm missing something, but from the data returned by Conseil it looks like I cannot directly determine the source, right? It only returns these 5 fields:
```
Block Hash: BMY2qp1Dym6t47vCQSBZ9Z5ySYUebh5oeoxpWUrpZyEyzykFX4Z
Block Level: 452539
Kind: Ballot
Op Group Hash: opNjvuYFSiHRFBAfDrXkaDxpFfG6WjYCHjbKWJGS9nrFxgUnUZD
Timestamp: 2019 May 25, 14:37
```

I would expect it to include at least the source and also the actual ballot vote (#452). Is there a reason it's not there?

Our use case is that we display operations depending on the kind, and right now it always returns an empty list for the ballot kind because there's no source.
