### ISSUE TITLE
Improve accounts dataset

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#501]
Account revelation and activation flags should be added to the accounts table. They should default to false.

**Comment by ivanopagano** [comment]
Ok, maybe additional info might be useful here.
If I understand correctly, that data is not available directly with the tezos RPC endpoint for accounts/contracts.

Does it mean that we need to infer this by looking at the blocks' operations and mark when each specific account id is involved in the revelation and activation operations?

**Comment by anonymoussprocket** [comment]
Yes, both account activation and revelation are operations.

**Comment by anonymoussprocket** [comment]
There should a process outside of the main Lorre loop that looks at accounts touched on a particular block to see if their status needs to be updated. If there is an `activate_account` or a `reveal`, the appropriate flag should be updated for the affected account. In the case of an `activate_account` message, the account id of interest is in the `pkh` field, for `reveal`s it's in `source`.

**Comment by ivanopagano** [comment]
Should this be a real os process running totally indipendently of Lorre, or is it a concurrent thread operating independently but still launched with Lorre, and stopped with it?

**Comment by anonymoussprocket** [comment]
Independent process that doesn't even know that Lorre exists

**Comment by vishakh** [comment]
@piotrkosecki Here is an updated spec for this ticket:

The objective is to add an `isActivated` flag to the `accounts` and `accounts_history` tables. 

When a new account is added or an account is updated, we should perform a check to see whether the account has been activated and set the `isActivated` flag accordingly. 

The check itself consists of querying the database to see whether there were any `activate_account` operations with the given account ID as `pkh`. If there are zero such operations, the flag should be set to false but true otherwise. 

@ivanopagano already did work on this ticket and had opened a PR therefore you should review his work first. Please keep in mind we had to close the PR for now because we want to avoid adding a new executable for now and instead want to do this work as part of the Lorre main loop.
