### ISSUE TITLE
Post-process ballot and proposal data

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#521]
This issue depends on #520.

Create a new table that combines the ballot and proposal information in a meaningful way. This is conceptually similar to the way we already process fees. The idea is to associate block level, vote count (yea, nay, pass), voted stake total (yea, nay, pass) (sum of the balances of the voters) and proposal hash.

Note this process should occur outside of the mail Lorre loop and should potentially be runnable independently of the rest of the chain loading code on separate hardware.

**Comment by ba205** [comment]
Logic for Algorithm:

**Tezos RPC Routes**

GET ../<block_id>/context/delegates/<pkh>/staking_balance
{{protocol}}://{{hostname}}:{{port}}/{{path_prefix}}/chains/main/blocks/head/votes/current_period_kind

**Database Schema**

  case class VotesRow(
      timestamp: java.sql.Timestamp,
      cycle: Option[Int] = None,
      level: Option[Int] = None,
      proposalHash: String,
      yayCount: Option[Int] = None,
      nayCount: Option[Int] = None,
      passCount: Option[Int] = None,
      yayStake: Option[scala.math.BigDecimal] = None,
      nayStake: Option[scala.math.BigDecimal] = None,
      passStake: Option[scala.math.BigDecimal] = None,
      totalStake: Option[scala.math.BigDecimal] = None,
      periodKind: String,
      periodIndex: Option[Int] = None
     )

**Algorithm**
-Fetch range of block levels to be queried for operations, from head level in Votes Table to head Level in Blocks Table
-For each block level
  -fetch voting fields from database, via ballot operation if proposalKind is in testing vote or promotion vote period, proposal operation otherwise, group by block level, as aggregation is done via that
  -do post processing calculations for stakes/counts, if ballot
  -create database rows, and write

**Comment by piotrkosecki** [comment]
@ba205 I think there is something wrong with the Tezos routes or maybe I misunderstood the way to use them - I can't make those routes to work, can you double check them?

**Comment by vishakh** [comment]
@piotrkosecki  The previous spec need to be greatly amended. Here is the latest spec. I would recommend creating a fresh PR and reusing the bits from the old PR which make sense. 

A new governance table should track the currently active Tezos governance proposal and the corresponding votes. 

The table schema should be:

CREATE TABLE tezos.governance (
    voting_period integer NOT NULL,
    voting_period_kind character varying NOT NULL,
    cycle integer,
    level integer,
    block_hash character varying NOT NULL,
    proposal_hash character varying NOT NULL,
    yay_count integer,
    nay_count integer,
    pass_count integer,
    yay_rolls numeric,
    nay_rolls numeric,
    pass_rolls numeric,
    total_rolls numeric,
);

The primary key should be (block_hash, proposal_hash). There should be indexes on block_hash and proposal_hash.

/chains/main/blocks/{block} provides:
- voting_period
- voting_period_kind
- cycle
- level
- block_hash

/chains/main/blocks/{block}/votes/current_proposal provides:
- proposal_hash

/chains/main/blocks/head/votes/ballots provides:
- yay_count
- nay_count
- pass_count

For calculating yay_rolls, nay_rolls, pass_rolls and total_rolls:
- Call `chains/main/blocks/{block}}/votes/ballot_list` to get a list of all ballots cast and store it in memory.
- Call `chains/main/blocks/{block}/votes/listings` to get a list of each baker's rolls and store it in memory.
- Using both datasets, calculate the number of rolls corresponding to yays, nays and passes and the totals.

There are four governance periods. 

In the 'Proposal' period, the later two RPC calls will not provide any data so the corresponding fields should be left blank. 

In the 'Testing' period, the last RPC call will not provide any data so the corresponding fields should be left blank.

In the `Testing Vote` and 'Promotion Vote' periods, all fields should be available. 

@anonymoussprocket Left TODO:
- Add columns with block-specific ballot information rather than running totals.
- Add rows for `proposal` governance period.
