### ISSUE TITLE
Examine Lorre for performance improvements

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#597]
As Lorre is now capturing many more data types than before and for a greater number of blocks, the time for full sync has gone up. We should examine the Lorre logic, especially database writes, to identify and remedy bottlenecks and generally improve performance. 

Suggested approach:
- Run Lorre locally for around 10,000 blocks and save the logs.
- Examine the logs for a typical iteration and find the bits which seem to be taking the longest.
- Validate any findings from above and try to find remedies. 
- Try to find ways overall of reducing the number of distinct database inserts.

**Comment by ivanopagano** [comment]
Without evidence of the eventual speedup (need to measure) I can think of

Removing the foreign key to `blocks` in the `accounts_checkpoint`

- Consistency of the accounts makes sense even if done only once the whole entity is saved. This should improve the writes throughput on the checkpoint table
- Once the FK is gone, we can reverse the save operation order, so that before saving the blocks we make a log of the accounts to load. This can remove the transactional boundary wrapping the whole operation, because if the operation fails on the second step (storing blocks), we have lost no critical data anyway, we can rerun the cycle with no risks. Removing this transaction boundary might show up a little improvements in performance.

**Comment by vishakh** [comment]
Reopening this ticket so @ivanopagano can look into improving DB concurrency for better Lorre performance.
