### ISSUE TITLE
Baker flag in accounts table

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#604]
Similar to the work in #501, add a flag to the accounts table to show if the address is baking.

**Comment by vishakh** [comment]
In order to add this flag while saving down account data, we should use the data from the `/chains/main/blocks/head/votes/listings` route of the Tezos node. If a given account has an entry in the results, it's `isBaker` value should be set to true, false otherwise.

The above route gives a list of active bakers and the number of rolls they control. If an account is not mentioned there, it is not a baker. 

Please keep in mind we might already be querying that route so we should ideally not query it a second time (if possible).

**Comment by ba205** [comment]
> In order to add this flag while saving down account data, we should use the data from the `/chains/main/blocks/head/votes/listings` route of the Tezos node. If a given account has an entry in the results, it's `isBaker` value should be set to true, false otherwise.

As mentioned in the call yesterday, if I understood correctly, an account becomes a baker if it has a delegation operation involving itself. An account can also have nonzero balance of rolls without being a baker.

My concern: is it possible for an account to be listed here without performing that self-delegation operation? If not, then this approach works. Otherwise, we have to check and see if a specific account is touched by that kind of operation before performing this check.

**Comment by vishakh** [comment]
@ba205 I checked a few accounts using Arronax. `tz1Syu3KacZ8cy4286a4vaCeoMtwqVKHkaoj` has  22,774,503 tz but does not show up in the `rolls` results.

I therefore think we are good.

**Comment by ivanopagano** [comment]
Does the flag switch on and off based on baking cycle?
