### ISSUE TITLE
Investigate protocol 005 airdrop balance update

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#607]
It appears that Conseil is not picking up the 1utz airdrop that occurred at the time of the upgrade. Consider these two results:

[A](https://arronax-beta.cryptonomic.tech?e=Tezos%20Mainnet/accounts&q=eyJmaWVsZHMiOlsiYWNjb3VudF9pZCIsIm1hbmFnZXIiLCJkZWxlZ2F0ZV92YWx1ZSIsImJhbGFuY2UiXSwicHJlZGljYXRlcyI6W3siZmllbGQiOiJhY2NvdW50X2lkIiwib3BlcmF0aW9uIjoiZXEiLCJzZXQiOlsidHoxV1JkV3A5NjljdG5hSFV3VXZma3JLRlV0SkFhQXZ3ajE3Il0sImludmVyc2UiOmZhbHNlfV0sIm9yZGVyQnkiOlt7ImZpZWxkIjoiYmxvY2tfbGV2ZWwiLCJkaXJlY3Rpb24iOiJkZXNjIn1dLCJhZ2dyZWdhdGlvbiI6W10sImxpbWl0IjoxMDAwfQ) vs [B](https://tzstats.com/account/tz1WRdWp969ctnaHUwUvfkrKFUtJAaAvwj17)

A shows 0.000000, B has 0.000001

**Comment by ba205** [comment]
Here is a potential spec for the logic:

In Lorre.scala:
-In mainLoop function:
  -At the end of processing:
    -using db handle in Lorre.scala, run ProtocolUpgrades.isProtocol005Active
    -if protocol005 is active and !config.hasPath("protocol005Updated") 
      -run ProtocolUpgrades.updateAccountBalancesForProtocol005
      -write new value "protocol005Updated" to config, with value true

reference.conf
-New variable "protocol005BlockLevel" set to 655361.
-After protocol005 has been detected, and the account balance fix has been updated, a new value "protocol005Updated" will be written as true, so that logic is run exactly once.

ProtocolUpgrades.scala
-File under tezos namespace.
-Retrieve new "protocol005BlockLevel" variable from configuration.
-Function "isProtocol005Active": DBIO[Boolean]
  -Use TezosDatabaseOperations "maxBlockLevel" function.
  -Return whether or not "maxBlockLevel" >= protocol005BlockLevel.
-Function "fetchProtocol005UpdatedAccounts" (type?).
  -Run a tezos node query to fetch the block data from protocol005BlockLevel.
  -Save list of account ids with total balance "0.000001" (or if database has units microtez, "1").
-Function "updateAccountBalancesForProtocol005":
  -Run fetchProtocol005UpdatedAccounts to collect list of account ids.
  -For each account id:
    -Get latest row from accounts table for that id.
    -Create a new row with the exact same fields, except balance is updated by 1 (if in microtez), or 0.000001 (if in tez)
    -Write row to db
    -Should this be transactional?

**Comment by vishakh** [comment]
Latest spec:

The Lorre config file should accept a list of all block heights at which a full refresh of all accounts should be conducted. 

The manner in which this is conducted is left to @ivanopagano.

For proto5, we will simply add an entry to `mainnet.conf` which will stupidly refresh all account balances.

**Comment by anonymoussprocket** [comment]
We should benchmark this process.

The trigger levels should be a function of governance period.

**Comment by ivanopagano** [comment]
> The trigger levels should be a function of governance period.

How so? Would you mind to kindly elaborate?
