### ISSUE TITLE
RFC: Create an intermediate store for Tezos RPC data

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#633]
Due to the numerous changes we make to the Conseil DB schema, every release requires a full resync. These resync are becoming more expensive as the chain grows and the performance of the Tezos node RPC also degrades. Therefore, we should consider storing Tezos RPC data in an intermediate proxy store so resyncs become significantly more efficient. 

This work would be done as a new component outside of Conseil. It would expose an API identical to the Tezos RPC API but fetch data from its own store. The store would contain results from all the RPC calls we need. When additional RPC calls need to be stored, they could be selectively picked up.

The store itself could be any simple and performant key-value store or something more fancy, as long as the performance is expected to be at least an order of magnitude better than that of the Tezos node. The keys would be the RPC endpoints and the values simply the returned JSON. If we use a document store, this component could be directly useful on its own.

Lorre would be completely agnostic to its data source as it would be dealing with a uniform interface whether it hits the Tezos node directly or this new component. 

Initial questions:
- Does this approach make sense?
- What store is best for this component, especially if we want to keep the option of offering this as a public service?
- Are there are other important considerations we should discuss?

**Comment by ivanopagano** [comment]
I totally agree as I was thinking along the same lines for awhile.

I'd say that Mongo might be a cheap solution. It's fairly easy to use, it's an established product, there are existing libraries to work with it, directly in scala.

I've seen comments that preferred couchDb as a better product, in terms of quality, but I don't know about its stability and the existing access tools.

**Comment by ivanopagano** [comment]
I also feel that this might additionally help in fork detection and correction, but only if the additional component would be made available to the general public.

**Comment by vishakh** [comment]
> I totally agree as I was thinking along the same lines for awhile.
> 
> I'd say that Mongo might be a cheap solution. It's fairly easy to use, it's an established product, there are existing libraries to work with it, directly in scala.
> 
> I've seen comments that preferred couchDb as a better product, in terms of quality, but I don't know about its stability and the existing access tools.

I have used CouchDB in the past and found it stable and super easy to use.

**Comment by vishakh** [comment]
> I also feel that this might additionally help in fork detection and correction, but only if the additional component would be made available to the general public.

Can you explain why you think it would help with fork detection only if it is made available to the general public?

**Comment by ivanopagano** [comment]
> > I also feel that this might additionally help in fork detection and correction, but only if the additional component would be made available to the general public.
> 
> Can you explain why you think it would help with fork detection only if it is made available to the general public?

I mean two separate things, actually
1. it would certainly simplify the fork detection and correction, since we need only check a path in the json string to identify the block hash (and maybe level?) to identify inconsistencies and eventually reload from the node. This could be done internally by the new "rpc proxy" component.
2. to make the forking logic available to any developer, the proxy can not be used exclusively as an internal architectural choice for the Cryptonomic infrastructure, but needs be a part of the overall architecture available to any user.

Otherwise the forking logic should be part of the main Lorre process, like we did with the existing work branches. So that the proxy could be deployed as a layer transparent to lorre itself.
In this case we can think of deploying it only on internal infrastructure, e.g. for nautilus.

We can always rethink the forking detection to work on the unparsed json, but that would mean redesigning a significant piece of the existing node client in Lorre.

**Comment by vishakh** [comment]
https://github.com/Cryptonomic/Pencroff/issues/1 opened so we can do an initial evaluation

**Comment by vishakh** [comment]
Closing this ticket as https://github.com/Cryptonomic/Pencroff/issues/1 supercedes it.
