### ISSUE TITLE
account_history is missing deactivated flag

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#653]
Baker "active" flag should be tracked in this table.

**Comment by vishakh** [comment]
What's the link between "deactivated" and the "baker active" flag?

**Comment by anonymoussprocket** [comment]
We keep track of is_baker flag in account history, but we don't track if they at some point become deactivated. An account can be both a baker and be deactivated.

**Comment by vishakh** [comment]
Since https://tezos.stackexchange.com/questions/2037/is-baker-deactivation-explicitly-recorded-on-chain/2038 suggests there is no way to directly capture baker deactivations from the blockchain, I suggest we change our current algorithm in another way. 

During the accounts fetching process, if the current block is the first block of a new cycle, i.e. `block_level % cycle_size == 1`, we check whether each account in the DB marked as a baker is still active. If an account is no longer active as a baker, we set the `is_baker_deactivated` flag to `true`. 

Conversely, if we see an account registering as a baker, we should set the `is_baker_deactivated` flag to `false`. 

Furthermore, to make the table semantics better, I suggest we rename the column to `is_active_baker` and flip the meanings of `true` and `false`. 

The current logic as its implemented is incorrect. We only check for deactivations when a delegation operation shows up with the given baker as the delegate. 

@anonymoussprocket @bhaskarkishore @piotrkosecki @ivanopagano
