### ISSUE TITLE
Optimize the docker build

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#689]
Testing a local publish of the docker image I've found a few improvements to make:

* the docker build file naively copies the whole content of the current directory to the container to run the compilation of conseil, where we might select to copy only the needed files. 
  * This is especially relevant if for any reason I'm keeping temporary files in the project for my local development and need to publish locally for testing
* it looks like the project is compiled twice during the docker build, each time starting from scratch (therefore downloading all dependencies, and compiling the scala bridge twice): should verify if that is true and figure out how to prevent that

**Comment by vishakh** [comment]
@piotrkosecki You might want to have a look.

**Comment by ivanopagano** [comment]
I'd also add that fixing the published version like that might turn out to be a brittle design.
The "SNAPSHOT" label is only there if you're not on clean git commit. But it will not have the suffix otherwise.
In other words, now it works only if you have a dirty git status

**Comment by piotrkosecki** [comment]
> it looks like the project is compiled twice during the docker build, each time starting from scratch (therefore downloading all dependencies, and compiling the scala bridge twice): should verify if that is true and figure out how to prevent that

It is compiled once to be sure we have up to date `BuildInfo.scala` file - but this does not download all of the dependencies, because it is being done outside of container(unless `.ivy2/` is empty).
Second time it is compiled during docker build and it needs to download the dependencies.

> I've also just realised that the conseil-postgres service depends on conseil service, and I'm not sure to see why is so...?

That's my mistake - I thought that container must be up an running to get the `conseil.sql` file - tested and apparently that's not the case.
